// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupPayload struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupPayload) Reset()         { *m = SignupPayload{} }
func (m *SignupPayload) String() string { return proto.CompactTextString(m) }
func (*SignupPayload) ProtoMessage()    {}
func (*SignupPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{0}
}

func (m *SignupPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupPayload.Unmarshal(m, b)
}
func (m *SignupPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupPayload.Marshal(b, m, deterministic)
}
func (m *SignupPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupPayload.Merge(m, src)
}
func (m *SignupPayload) XXX_Size() int {
	return xxx_messageInfo_SignupPayload.Size(m)
}
func (m *SignupPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SignupPayload proto.InternalMessageInfo

func (m *SignupPayload) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SignupPayload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// SignupRequest ...
type SignUpReq struct {
	// API versioning: it is my best practice to specify version explicitly
	Api                  string         `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Payload              *SignupPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{1}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignUpReq) GetPayload() *SignupPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

// SignupResponse returns response of received command
type SignUpRes struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// UUID of created signup request
	Uuid                 []byte   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRes) Reset()         { *m = SignUpRes{} }
func (m *SignUpRes) String() string { return proto.CompactTextString(m) }
func (*SignUpRes) ProtoMessage()    {}
func (*SignUpRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{2}
}

func (m *SignUpRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRes.Unmarshal(m, b)
}
func (m *SignUpRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRes.Marshal(b, m, deterministic)
}
func (m *SignUpRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRes.Merge(m, src)
}
func (m *SignUpRes) XXX_Size() int {
	return xxx_messageInfo_SignUpRes.Size(m)
}
func (m *SignUpRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRes.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRes proto.InternalMessageInfo

func (m *SignUpRes) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignUpRes) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func init() {
	proto.RegisterType((*SignupPayload)(nil), "v1.SignupPayload")
	proto.RegisterType((*SignUpReq)(nil), "v1.SignUpReq")
	proto.RegisterType((*SignUpRes)(nil), "v1.SignUpRes")
}

func init() { proto.RegisterFile("auth_service.proto", fileDescriptor_0f39bb026ca10b68) }

var fileDescriptor_0f39bb026ca10b68 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x86, 0xe5, 0xa4, 0x4d, 0xbf, 0x4e, 0xdb, 0x8f, 0x32, 0x02, 0x14, 0x59, 0x2c, 0x8c, 0x57,
	0x28, 0x10, 0x4f, 0x1c, 0xb2, 0x0a, 0x42, 0xa2, 0xb0, 0x43, 0x08, 0x55, 0x8e, 0x90, 0xd8, 0x55,
	0xa7, 0xf6, 0x91, 0x3d, 0xc5, 0x9e, 0x19, 0xe6, 0xc7, 0x21, 0x2c, 0xb9, 0x04, 0xd8, 0x71, 0x5b,
	0x5c, 0x00, 0x0b, 0xb8, 0x10, 0xe4, 0x71, 0x02, 0xaa, 0xca, 0x6a, 0xce, 0xcf, 0x3b, 0xcf, 0x7b,
	0x74, 0x66, 0x08, 0x05, 0x67, 0xab, 0x0b, 0x83, 0xba, 0xe5, 0x39, 0x26, 0x4a, 0x4b, 0x2b, 0xe9,
	0xa0, 0x4d, 0xc3, 0xfb, 0xa5, 0x94, 0x65, 0x8d, 0x0c, 0x14, 0x67, 0x20, 0x84, 0xb4, 0x60, 0xb9,
	0x14, 0xa6, 0x57, 0x84, 0x8f, 0xfd, 0x91, 0x4f, 0x4b, 0x14, 0x53, 0xb3, 0x86, 0xb2, 0x44, 0xcd,
	0xa4, 0xf2, 0x8a, 0x9b, 0xea, 0xb8, 0x20, 0x27, 0x2b, 0x5e, 0x0a, 0xa7, 0xce, 0x61, 0x53, 0x4b,
	0x28, 0xe8, 0x03, 0x72, 0x5c, 0x70, 0xa3, 0x6a, 0xd8, 0x5c, 0x08, 0x68, 0x70, 0x1c, 0x44, 0xc1,
	0xc3, 0xc3, 0xec, 0x68, 0x5b, 0x7b, 0x03, 0x0d, 0xd2, 0x3b, 0x64, 0x1f, 0x1b, 0xe0, 0xf5, 0x78,
	0xe0, 0x7b, 0x7d, 0x42, 0x43, 0xf2, 0x9f, 0x02, 0x63, 0xd6, 0x52, 0x17, 0xe3, 0xa1, 0x6f, 0xfc,
	0xc9, 0xe3, 0x57, 0xe4, 0xb0, 0x73, 0x79, 0xab, 0x32, 0xfc, 0x40, 0x4f, 0xc9, 0x10, 0x14, 0xdf,
	0x82, 0xbb, 0x90, 0x3e, 0x22, 0x07, 0xaa, 0xb7, 0xf7, 0xc8, 0xa3, 0xf9, 0xed, 0xa4, 0x4d, 0x93,
	0x6b, 0x73, 0x65, 0x3b, 0x45, 0x9c, 0xfe, 0x65, 0x99, 0x7f, 0xb0, 0x28, 0xd9, 0x73, 0x8e, 0xf7,
	0xa0, 0xe3, 0xcc, 0xc7, 0xf3, 0x15, 0xa1, 0x67, 0xce, 0x56, 0x2f, 0x65, 0xd3, 0x80, 0x28, 0x56,
	0xfd, 0x42, 0xe9, 0x33, 0x32, 0xea, 0x41, 0xf4, 0x64, 0x67, 0xe7, 0x07, 0x0c, 0xaf, 0xa5, 0x26,
	0xbe, 0xfb, 0xf9, 0xfb, 0xaf, 0xaf, 0x83, 0x5b, 0x31, 0x61, 0x6d, 0xca, 0x8c, 0x1f, 0x6a, 0x19,
	0x4c, 0x5e, 0xfc, 0x0c, 0xbe, 0x9c, 0xfd, 0x08, 0xe8, 0x86, 0xdc, 0xeb, 0xd8, 0x28, 0x2c, 0xcf,
	0xfd, 0x66, 0xa3, 0xed, 0x83, 0xc5, 0xef, 0xc8, 0xff, 0xe7, 0x5a, 0x5e, 0x61, 0x6e, 0xa3, 0xd7,
	0xb0, 0x91, 0xce, 0xd2, 0x49, 0x65, 0xad, 0x32, 0x4b, 0xc6, 0x4a, 0x6e, 0x2b, 0x77, 0x99, 0xe4,
	0xb2, 0x61, 0xc5, 0x27, 0x2e, 0x2c, 0x68, 0xc3, 0x54, 0xaf, 0x9d, 0xd6, 0x5e, 0x1b, 0x86, 0xbb,
	0x46, 0xf2, 0xbe, 0x86, 0x96, 0x0b, 0xf3, 0xbc, 0xec, 0xd6, 0xdc, 0xdd, 0x99, 0xef, 0xcf, 0x92,
	0x59, 0x92, 0x4e, 0x82, 0x60, 0x7e, 0x0a, 0x4a, 0xd5, 0x5b, 0x63, 0x76, 0x65, 0xa4, 0x58, 0xde,
	0xa8, 0x64, 0x4f, 0xc9, 0x70, 0x31, 0x5b, 0xd0, 0x05, 0x99, 0x64, 0x68, 0x9d, 0x16, 0x58, 0x44,
	0xeb, 0x0a, 0x45, 0x64, 0x2b, 0x8c, 0x34, 0x1a, 0xe9, 0x74, 0x8e, 0x51, 0x21, 0xd1, 0x44, 0x42,
	0xda, 0x08, 0x3f, 0x72, 0x63, 0x13, 0x3a, 0x22, 0x7b, 0xdf, 0x06, 0xc1, 0xc1, 0xe5, 0xc8, 0x7f,
	0x93, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x88, 0x11, 0xf2, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthCommandServiceClient is the client API for AuthCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthCommandServiceClient interface {
	// SignUp ...
	SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpRes, error)
}

type authCommandServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthCommandServiceClient(cc *grpc.ClientConn) AuthCommandServiceClient {
	return &authCommandServiceClient{cc}
}

func (c *authCommandServiceClient) SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpRes, error) {
	out := new(SignUpRes)
	err := c.cc.Invoke(ctx, "/v1.AuthCommandService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCommandServiceServer is the server API for AuthCommandService service.
type AuthCommandServiceServer interface {
	// SignUp ...
	SignUp(context.Context, *SignUpReq) (*SignUpRes, error)
}

// UnimplementedAuthCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthCommandServiceServer struct {
}

func (*UnimplementedAuthCommandServiceServer) SignUp(ctx context.Context, req *SignUpReq) (*SignUpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterAuthCommandServiceServer(s *grpc.Server, srv AuthCommandServiceServer) {
	s.RegisterService(&_AuthCommandService_serviceDesc, srv)
}

func _AuthCommandService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCommandServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthCommandService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCommandServiceServer).SignUp(ctx, req.(*SignUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AuthCommandService",
	HandlerType: (*AuthCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _AuthCommandService_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}
