// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpPayload struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpPayload) Reset()         { *m = SignUpPayload{} }
func (m *SignUpPayload) String() string { return proto.CompactTextString(m) }
func (*SignUpPayload) ProtoMessage()    {}
func (*SignUpPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{0}
}

func (m *SignUpPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpPayload.Unmarshal(m, b)
}
func (m *SignUpPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpPayload.Marshal(b, m, deterministic)
}
func (m *SignUpPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpPayload.Merge(m, src)
}
func (m *SignUpPayload) XXX_Size() int {
	return xxx_messageInfo_SignUpPayload.Size(m)
}
func (m *SignUpPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpPayload proto.InternalMessageInfo

func (m *SignUpPayload) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SignUpPayload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// SignupRequest ...
type SignUpRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api                  string         `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Payload              *SignUpPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{1}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignUpRequest) GetPayload() *SignUpPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

// SignupResponse returns response of received command
type SignUpResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// UUID of created signup request
	Uuid                 []byte   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{2}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignUpResponse) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

type Credentials struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{3}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// SignInRequest ...
type SignInRequest struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{4}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignInRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*SignUpPayload)(nil), "v1.SignUpPayload")
	proto.RegisterType((*SignUpRequest)(nil), "v1.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "v1.SignUpResponse")
	proto.RegisterType((*Credentials)(nil), "v1.Credentials")
	proto.RegisterType((*SignInRequest)(nil), "v1.SignInRequest")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor_0dff099eb2e3dfdb) }

var fileDescriptor_0dff099eb2e3dfdb = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x73, 0xd3, 0x30,
	0x10, 0x1d, 0xa5, 0x4d, 0x0a, 0x4a, 0xbf, 0xd0, 0x50, 0x26, 0x18, 0x86, 0x31, 0x3e, 0x31, 0x81,
	0xca, 0x49, 0xc8, 0x70, 0x08, 0x07, 0x28, 0x19, 0x98, 0x09, 0x87, 0xd2, 0x71, 0xe9, 0x99, 0x51,
	0xec, 0xc5, 0x11, 0xd8, 0x92, 0xb0, 0xe4, 0x84, 0x70, 0xe0, 0xc0, 0x4f, 0x80, 0x1b, 0x37, 0x7e,
	0x13, 0x7f, 0x81, 0x7f, 0xc0, 0x81, 0x2b, 0x63, 0xd9, 0x69, 0x52, 0x42, 0x2f, 0xb6, 0x76, 0xdf,
	0xfa, 0xed, 0x7b, 0xf2, 0xc3, 0xbb, 0xa1, 0x4c, 0x53, 0x26, 0x22, 0x4d, 0x55, 0x26, 0x8d, 0x24,
	0xb5, 0x69, 0xd7, 0xb9, 0x1d, 0x4b, 0x19, 0x27, 0xe0, 0x33, 0xc5, 0x7d, 0x26, 0x84, 0x34, 0xcc,
	0x70, 0x29, 0xaa, 0x09, 0xe7, 0x56, 0x85, 0xda, 0x6a, 0x9c, 0xbf, 0xf5, 0x21, 0x55, 0x66, 0x5e,
	0x81, 0x0f, 0xec, 0x2b, 0x3c, 0x8c, 0x41, 0x1c, 0xea, 0x19, 0x8b, 0x63, 0xc8, 0x7c, 0xa9, 0xec,
	0xe7, 0xeb, 0x54, 0x5e, 0x84, 0x77, 0x4e, 0x79, 0x2c, 0xce, 0xd4, 0x09, 0x9b, 0x27, 0x92, 0x45,
	0xe4, 0x2e, 0xde, 0x8e, 0xb8, 0x56, 0x09, 0x9b, 0xbf, 0x11, 0x2c, 0x85, 0x16, 0x72, 0xd1, 0xbd,
	0xab, 0x41, 0xb3, 0xea, 0x1d, 0xb3, 0x14, 0xc8, 0x75, 0x5c, 0x87, 0x94, 0xf1, 0xa4, 0x55, 0xb3,
	0x58, 0x59, 0x10, 0x07, 0x5f, 0x51, 0x4c, 0xeb, 0x99, 0xcc, 0xa2, 0xd6, 0x86, 0x05, 0xce, 0x6b,
	0xef, 0x78, 0xb1, 0x25, 0x80, 0x0f, 0x39, 0x68, 0x43, 0xf6, 0xf1, 0x06, 0x53, 0xbc, 0x22, 0x2f,
	0x8e, 0xe4, 0x3e, 0xde, 0x52, 0xa5, 0x04, 0x4b, 0xdb, 0xec, 0x5d, 0xa3, 0xd3, 0x2e, 0xbd, 0xa0,
	0x2d, 0x58, 0x4c, 0x78, 0x8f, 0xf0, 0xee, 0x82, 0x4f, 0x2b, 0x29, 0x34, 0xfc, 0x87, 0x90, 0xe0,
	0xcd, 0x3c, 0xe7, 0x25, 0xdb, 0x76, 0x60, 0xcf, 0xde, 0x13, 0xdc, 0x1c, 0x66, 0x10, 0x81, 0x30,
	0x9c, 0x25, 0x7a, 0x69, 0x04, 0x5d, 0x66, 0xa4, 0xf6, 0x8f, 0x91, 0xd7, 0xa5, 0x91, 0x91, 0xb8,
	0xdc, 0x48, 0x17, 0x37, 0xc3, 0xe5, 0x8e, 0xca, 0xcc, 0x5e, 0x61, 0x66, 0x65, 0x75, 0xb0, 0x3a,
	0xd3, 0xfb, 0x81, 0x70, 0xf3, 0x4c, 0x43, 0x76, 0x0a, 0xd9, 0x94, 0x87, 0x40, 0x5e, 0xe0, 0x46,
	0x69, 0x8f, 0xac, 0x5c, 0x42, 0xb5, 0xd1, 0x21, 0xab, 0xad, 0xd2, 0xbd, 0x77, 0xf0, 0xe5, 0xe7,
	0xaf, 0x6f, 0xb5, 0x3d, 0x0f, 0xfb, 0xd3, 0xae, 0xaf, 0x79, 0x2c, 0x72, 0x35, 0x40, 0x6d, 0xf2,
	0xb2, 0xe4, 0x19, 0x89, 0x25, 0xcf, 0xb9, 0x72, 0xe7, 0x06, 0x2d, 0x53, 0x44, 0x17, 0x29, 0xa2,
	0xcf, 0x8b, 0x14, 0xad, 0x73, 0x71, 0x31, 0x40, 0xed, 0x67, 0x7f, 0xd0, 0xd7, 0xa3, 0xdf, 0x88,
	0x7c, 0xc6, 0x07, 0x85, 0x52, 0x77, 0x58, 0x65, 0xd6, 0xd5, 0x95, 0xe6, 0x9b, 0x17, 0xdb, 0x47,
	0x27, 0xa3, 0x05, 0xe4, 0x0d, 0x71, 0xfd, 0x95, 0x9e, 0x01, 0x90, 0x3b, 0x13, 0x63, 0x94, 0x1e,
	0xf8, 0x7e, 0xcc, 0xcd, 0x24, 0x1f, 0xd3, 0x50, 0xa6, 0xbe, 0x2c, 0x90, 0xf2, 0xe9, 0x38, 0xd1,
	0x27, 0x2e, 0x0c, 0xcb, 0x34, 0x7d, 0x9f, 0xb0, 0x29, 0x17, 0xfa, 0x69, 0x5c, 0xfc, 0x91, 0x62,
	0xae, 0x57, 0xef, 0xd0, 0x0e, 0xed, 0x3a, 0x3b, 0x4c, 0x71, 0x6a, 0xa7, 0x8b, 0x6e, 0x1b, 0xa1,
	0xde, 0x3e, 0x53, 0x2a, 0xe1, 0xa1, 0x4d, 0xb5, 0xff, 0x4e, 0x4b, 0x31, 0x58, 0xeb, 0x04, 0x8f,
	0xf1, 0x46, 0xbf, 0xd3, 0x27, 0x7d, 0xdc, 0x0e, 0xc0, 0xe4, 0x99, 0x80, 0xc8, 0x9d, 0x4d, 0x40,
	0xb8, 0x66, 0x02, 0x6e, 0x06, 0x5a, 0xe6, 0x59, 0x08, 0x6e, 0x24, 0x41, 0xbb, 0x42, 0x1a, 0x17,
	0x3e, 0x72, 0x6d, 0x28, 0x69, 0xe0, 0xcd, 0xef, 0x35, 0xb4, 0x35, 0x6e, 0xd8, 0x0b, 0x7a, 0xf8,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x04, 0xe9, 0x01, 0x2b, 0xa8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// SignUp ...
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	// SignIn...
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.UserService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// SignUp ...
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	// SignIn...
	SignIn(context.Context, *SignInRequest) (*empty.Empty, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedUserServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _UserService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _UserService_SignIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commands.proto",
}
