// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queries.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupPayload struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupPayload) Reset()         { *m = SignupPayload{} }
func (m *SignupPayload) String() string { return proto.CompactTextString(m) }
func (*SignupPayload) ProtoMessage()    {}
func (*SignupPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4428c075ebff26, []int{0}
}

func (m *SignupPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupPayload.Unmarshal(m, b)
}
func (m *SignupPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupPayload.Marshal(b, m, deterministic)
}
func (m *SignupPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupPayload.Merge(m, src)
}
func (m *SignupPayload) XXX_Size() int {
	return xxx_messageInfo_SignupPayload.Size(m)
}
func (m *SignupPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SignupPayload proto.InternalMessageInfo

func (m *SignupPayload) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SignupPayload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// SignupRequest ...
type SignUpReq struct {
	// API versioning: it is my best practice to specify version explicitly
	Api                  string         `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Payload              *SignupPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4428c075ebff26, []int{1}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignUpReq) GetPayload() *SignupPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

// SignupResponse returns response of received command
type SignUpRes struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// UUID of created signup request
	Uuid                 []byte   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRes) Reset()         { *m = SignUpRes{} }
func (m *SignUpRes) String() string { return proto.CompactTextString(m) }
func (*SignUpRes) ProtoMessage()    {}
func (*SignUpRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4428c075ebff26, []int{2}
}

func (m *SignUpRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRes.Unmarshal(m, b)
}
func (m *SignUpRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRes.Marshal(b, m, deterministic)
}
func (m *SignUpRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRes.Merge(m, src)
}
func (m *SignUpRes) XXX_Size() int {
	return xxx_messageInfo_SignUpRes.Size(m)
}
func (m *SignUpRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRes.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRes proto.InternalMessageInfo

func (m *SignUpRes) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignUpRes) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

type Credentials struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4428c075ebff26, []int{3}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// SignInRequest ...
type SignInReq struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4428c075ebff26, []int{4}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignInReq) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*SignupPayload)(nil), "v1.SignupPayload")
	proto.RegisterType((*SignUpReq)(nil), "v1.SignUpReq")
	proto.RegisterType((*SignUpRes)(nil), "v1.SignUpRes")
	proto.RegisterType((*Credentials)(nil), "v1.Credentials")
	proto.RegisterType((*SignInReq)(nil), "v1.SignInReq")
}

func init() { proto.RegisterFile("queries.proto", fileDescriptor_1a4428c075ebff26) }

var fileDescriptor_1a4428c075ebff26 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x95, 0x93, 0x36, 0xfd, 0xba, 0x6e, 0xd4, 0x7e, 0x2b, 0x40, 0x91, 0x85, 0x90, 0xf1, 0x09,
	0x05, 0x6a, 0xc7, 0x21, 0xa7, 0x20, 0x04, 0x85, 0x53, 0x10, 0x82, 0xe0, 0xaa, 0x67, 0xb4, 0xb5,
	0x47, 0xce, 0x82, 0xb3, 0xbb, 0xdd, 0x59, 0x27, 0x84, 0x03, 0x07, 0x7e, 0x02, 0xdc, 0xf8, 0x5b,
	0xfc, 0x05, 0xfe, 0x01, 0x07, 0xae, 0xc8, 0x6b, 0x87, 0xa4, 0xb4, 0x5c, 0xec, 0x9d, 0x37, 0x4f,
	0x6f, 0xde, 0x1b, 0x0d, 0xe9, 0x5e, 0x94, 0xa0, 0x39, 0x60, 0xa8, 0xb4, 0x34, 0x92, 0xb6, 0x16,
	0xb1, 0x77, 0x3b, 0x97, 0x32, 0x2f, 0x20, 0x62, 0x8a, 0x47, 0x4c, 0x08, 0x69, 0x98, 0xe1, 0x52,
	0x34, 0x0c, 0xef, 0x81, 0xfd, 0xa5, 0xc7, 0x39, 0x88, 0x63, 0x5c, 0xb2, 0x3c, 0x07, 0x1d, 0x49,
	0x65, 0x19, 0x57, 0xd9, 0x41, 0x46, 0xba, 0xa7, 0x3c, 0x17, 0xa5, 0x9a, 0xb2, 0x55, 0x21, 0x59,
	0x46, 0xef, 0x92, 0x83, 0x8c, 0xa3, 0x2a, 0xd8, 0xea, 0xad, 0x60, 0x73, 0xe8, 0x39, 0xbe, 0x73,
	0x6f, 0x3f, 0x71, 0x1b, 0xec, 0x15, 0x9b, 0x03, 0xbd, 0x41, 0x76, 0x61, 0xce, 0x78, 0xd1, 0x6b,
	0xd9, 0x5e, 0x5d, 0x50, 0x8f, 0xfc, 0xa7, 0x18, 0xe2, 0x52, 0xea, 0xac, 0xd7, 0xb6, 0x8d, 0x3f,
	0x75, 0xf0, 0x82, 0xec, 0x57, 0x53, 0xce, 0x54, 0x02, 0x17, 0xf4, 0x88, 0xb4, 0x99, 0xe2, 0x8d,
	0x70, 0xf5, 0xa4, 0xf7, 0xc9, 0x9e, 0xaa, 0xc7, 0x5b, 0x49, 0x77, 0xf8, 0x7f, 0xb8, 0x88, 0xc3,
	0x4b, 0xbe, 0x92, 0x35, 0x23, 0x88, 0x37, 0x5a, 0x78, 0x8d, 0x16, 0x25, 0x3b, 0x65, 0xc9, 0x6b,
	0xa1, 0x83, 0xc4, 0xbe, 0x83, 0x27, 0xc4, 0x7d, 0xae, 0x21, 0x03, 0x61, 0x38, 0x2b, 0x70, 0xe3,
	0xdf, 0xf9, 0x97, 0xff, 0xd6, 0x5f, 0xfe, 0xa7, 0xf5, 0xcc, 0x89, 0xb8, 0xde, 0x7f, 0x4c, 0xdc,
	0x74, 0xa3, 0xdf, 0x64, 0x38, 0xac, 0x32, 0x6c, 0x8d, 0x4d, 0xb6, 0x39, 0xc3, 0x97, 0xc4, 0x3d,
	0x43, 0xd0, 0xa7, 0xa0, 0x17, 0x3c, 0x05, 0xfa, 0x98, 0x74, 0xea, 0x50, 0xb4, 0xbb, 0x8e, 0x6e,
	0x97, 0xe5, 0x5d, 0x2a, 0x31, 0xb8, 0xf9, 0xf9, 0xfb, 0x8f, 0xaf, 0xad, 0xc3, 0x80, 0x44, 0x8b,
	0x38, 0x42, 0xbb, 0xa0, 0xb1, 0xd3, 0x7f, 0xf6, 0xcb, 0xf9, 0x72, 0xf2, 0xd3, 0xa1, 0x9f, 0x08,
	0xad, 0x44, 0xfd, 0x37, 0x25, 0xe8, 0x95, 0x8f, 0x8d, 0xf6, 0xad, 0x2d, 0xec, 0x64, 0x3a, 0x59,
	0xe3, 0xc1, 0x84, 0xb8, 0xaf, 0x71, 0x09, 0xe0, 0x57, 0x7d, 0xa4, 0x77, 0x66, 0xc6, 0x28, 0x1c,
	0x47, 0x51, 0xce, 0xcd, 0xac, 0x3c, 0x0f, 0x53, 0x39, 0x8f, 0x64, 0xd5, 0xaf, 0xbf, 0x9e, 0x97,
	0x7d, 0xe4, 0xc2, 0x30, 0x8d, 0xe1, 0xfb, 0x82, 0x2d, 0xb8, 0xc0, 0xa7, 0x79, 0xb5, 0xb7, 0x8a,
	0x37, 0xdc, 0x1d, 0x84, 0x83, 0x30, 0xf6, 0xba, 0x4c, 0xf1, 0xd0, 0xb2, 0x2b, 0xb4, 0xef, 0x38,
	0xc3, 0x23, 0xa6, 0x54, 0xc1, 0x53, 0x7b, 0x72, 0xd1, 0x3b, 0x94, 0x62, 0x7c, 0x05, 0x49, 0x1e,
	0x91, 0xf6, 0x68, 0x30, 0xa2, 0x23, 0xd2, 0x4f, 0xc0, 0x94, 0x5a, 0x40, 0xe6, 0x2f, 0x67, 0x20,
	0x7c, 0x33, 0x03, 0x5f, 0x03, 0xca, 0x52, 0xa7, 0xe0, 0x67, 0x12, 0xd0, 0x17, 0xd2, 0xf8, 0xf0,
	0x81, 0xa3, 0x09, 0x69, 0x87, 0xec, 0x7c, 0x6b, 0x39, 0x7b, 0xe7, 0x1d, 0x7b, 0xc6, 0x0f, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x86, 0x91, 0x1f, 0x32, 0x27, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// SignUp ...
	SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpRes, error) {
	out := new(SignUpRes)
	err := c.cc.Invoke(ctx, "/v1.UserService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// SignUp ...
	SignUp(context.Context, *SignUpReq) (*SignUpRes, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SignUp(ctx context.Context, req *SignUpReq) (*SignUpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignUp(ctx, req.(*SignUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _UserService_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queries.proto",
}
