// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSignupRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Pasword              string   `protobuf:"bytes,3,opt,name=pasword,proto3" json:"pasword,omitempty"`
	DisplayName          string   `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSignupRequest) Reset()         { *m = CreateSignupRequest{} }
func (m *CreateSignupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSignupRequest) ProtoMessage()    {}
func (*CreateSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{0}
}

func (m *CreateSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSignupRequest.Unmarshal(m, b)
}
func (m *CreateSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSignupRequest.Marshal(b, m, deterministic)
}
func (m *CreateSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSignupRequest.Merge(m, src)
}
func (m *CreateSignupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSignupRequest.Size(m)
}
func (m *CreateSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSignupRequest proto.InternalMessageInfo

func (m *CreateSignupRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSignupRequest) GetPasword() string {
	if m != nil {
		return m.Pasword
	}
	return ""
}

func (m *CreateSignupRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type CreateSignupResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Uuid                 []byte   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSignupResponse) Reset()         { *m = CreateSignupResponse{} }
func (m *CreateSignupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSignupResponse) ProtoMessage()    {}
func (*CreateSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{1}
}

func (m *CreateSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSignupResponse.Unmarshal(m, b)
}
func (m *CreateSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSignupResponse.Marshal(b, m, deterministic)
}
func (m *CreateSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSignupResponse.Merge(m, src)
}
func (m *CreateSignupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSignupResponse.Size(m)
}
func (m *CreateSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSignupResponse proto.InternalMessageInfo

func (m *CreateSignupResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSignupResponse) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSignupRequest)(nil), "v1.CreateSignupRequest")
	proto.RegisterType((*CreateSignupResponse)(nil), "v1.CreateSignupResponse")
}

func init() { proto.RegisterFile("user-service.proto", fileDescriptor_2a3086c73a75cdba) }

var fileDescriptor_2a3086c73a75cdba = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0xb2, 0x2b, 0x4c, 0x25, 0x56, 0x66, 0x11, 0x51, 0xc4, 0x21, 0xe4, 0x84, 0x0a,
	0x8d, 0xb7, 0xa5, 0xa7, 0xc2, 0x01, 0xd8, 0x3b, 0x87, 0xac, 0x10, 0xdc, 0x90, 0x37, 0x19, 0xa5,
	0x86, 0xc4, 0x63, 0x3c, 0x76, 0x0a, 0x7b, 0xe4, 0x13, 0xe0, 0xc6, 0x67, 0x81, 0xc4, 0x17, 0xf0,
	0x21, 0x28, 0x4e, 0x91, 0x76, 0xd5, 0x5e, 0xec, 0x99, 0xf7, 0x9e, 0xfd, 0xe4, 0x79, 0x66, 0xdc,
	0x13, 0xd8, 0x39, 0x81, 0xed, 0x54, 0x09, 0xb9, 0xb1, 0xe8, 0x90, 0x8f, 0xba, 0x45, 0xf2, 0xb0,
	0x46, 0xac, 0x1b, 0x10, 0xd2, 0x28, 0x21, 0xb5, 0x46, 0x27, 0x9d, 0x42, 0x4d, 0x83, 0x22, 0x79,
	0x1a, 0xb6, 0x72, 0x5e, 0x83, 0x9e, 0xd3, 0x56, 0xd6, 0x35, 0x58, 0x81, 0x26, 0x28, 0xf6, 0xd5,
	0xd9, 0x15, 0xbb, 0x77, 0x6e, 0x41, 0x3a, 0xb8, 0x50, 0xb5, 0xf6, 0xa6, 0x80, 0xcf, 0x1e, 0xc8,
	0xf1, 0x13, 0x36, 0x96, 0x46, 0xc5, 0x51, 0x1a, 0x3d, 0xbe, 0x5d, 0xf4, 0x25, 0x3f, 0x65, 0xb7,
	0xa0, 0x95, 0xaa, 0x89, 0x47, 0x01, 0x1b, 0x1a, 0x1e, 0xb3, 0x63, 0x23, 0x69, 0x8b, 0xb6, 0x8a,
	0xc7, 0x01, 0xff, 0xdf, 0xf2, 0x47, 0x6c, 0x5a, 0x29, 0x32, 0x8d, 0xfc, 0xfa, 0x41, 0xcb, 0x16,
	0xe2, 0x49, 0xa0, 0xef, 0xec, 0xb0, 0x37, 0xb2, 0x85, 0xec, 0x05, 0x3b, 0xbd, 0xe9, 0x4d, 0x06,
	0x35, 0xc1, 0x01, 0x73, 0xce, 0x26, 0xde, 0xab, 0x2a, 0x78, 0x4f, 0x8b, 0x50, 0x2f, 0x35, 0xe3,
	0x6f, 0x09, 0xec, 0x39, 0xb6, 0xad, 0xd4, 0xd5, 0xc5, 0x30, 0x25, 0xfe, 0x9e, 0x4d, 0xaf, 0xdf,
	0xc9, 0x1f, 0xe4, 0xdd, 0x22, 0x3f, 0xf0, 0xc2, 0x24, 0xde, 0x27, 0x06, 0xfb, 0xec, 0xfe, 0xb7,
	0xdf, 0x7f, 0x7f, 0x8c, 0xee, 0x66, 0x4c, 0x74, 0x0b, 0x41, 0x81, 0x5b, 0x47, 0xb3, 0xd7, 0x7f,
	0xa2, 0xef, 0xaf, 0x7e, 0x45, 0xbc, 0x61, 0xd3, 0xde, 0x36, 0xdd, 0xc5, 0x92, 0xbd, 0xbb, 0xd9,
	0xf3, 0x27, 0x1b, 0xe7, 0x0c, 0xad, 0x85, 0xa8, 0x95, 0xdb, 0xf8, 0xcb, 0xbc, 0xc4, 0x56, 0x20,
	0x6d, 0x01, 0x76, 0x6b, 0x85, 0xad, 0x54, 0x9a, 0x44, 0x9f, 0x6d, 0x92, 0x54, 0x57, 0x4a, 0x3b,
	0x69, 0x29, 0xff, 0xd4, 0xc8, 0x4e, 0x69, 0x7a, 0x59, 0xf7, 0x63, 0xed, 0x0f, 0x2d, 0xc7, 0x8b,
	0xfc, 0x6c, 0x16, 0x45, 0xcb, 0x13, 0x69, 0x4c, 0xa3, 0xca, 0x90, 0x9a, 0xf8, 0x48, 0xa8, 0xd7,
	0x7b, 0x48, 0xf1, 0x9c, 0x8d, 0x57, 0x67, 0x2b, 0xbe, 0x62, 0xb3, 0x02, 0x9c, 0xb7, 0x1a, 0xaa,
	0x74, 0xbb, 0x01, 0x9d, 0xba, 0x0d, 0xa4, 0x16, 0x08, 0xbd, 0x2d, 0x21, 0xad, 0x10, 0x28, 0xd5,
	0xe8, 0x52, 0xf8, 0xa2, 0xc8, 0xe5, 0xfc, 0x88, 0x4d, 0x7e, 0x8e, 0xa2, 0xe3, 0xcb, 0xa3, 0xf0,
	0x13, 0x9e, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x18, 0x0e, 0xb9, 0x0e, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserCommandServiceClient is the client API for UserCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCommandServiceClient interface {
	// Create new signup request
	CreateSignup(ctx context.Context, in *CreateSignupRequest, opts ...grpc.CallOption) (*CreateSignupResponse, error)
}

type userCommandServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserCommandServiceClient(cc *grpc.ClientConn) UserCommandServiceClient {
	return &userCommandServiceClient{cc}
}

func (c *userCommandServiceClient) CreateSignup(ctx context.Context, in *CreateSignupRequest, opts ...grpc.CallOption) (*CreateSignupResponse, error) {
	out := new(CreateSignupResponse)
	err := c.cc.Invoke(ctx, "/v1.UserCommandService/CreateSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCommandServiceServer is the server API for UserCommandService service.
type UserCommandServiceServer interface {
	// Create new signup request
	CreateSignup(context.Context, *CreateSignupRequest) (*CreateSignupResponse, error)
}

// UnimplementedUserCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserCommandServiceServer struct {
}

func (*UnimplementedUserCommandServiceServer) CreateSignup(ctx context.Context, req *CreateSignupRequest) (*CreateSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSignup not implemented")
}

func RegisterUserCommandServiceServer(s *grpc.Server, srv UserCommandServiceServer) {
	s.RegisterService(&_UserCommandService_serviceDesc, srv)
}

func _UserCommandService_CreateSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCommandServiceServer).CreateSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserCommandService/CreateSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCommandServiceServer).CreateSignup(ctx, req.(*CreateSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserCommandService",
	HandlerType: (*UserCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSignup",
			Handler:    _UserCommandService_CreateSignup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service.proto",
}
