// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSignupRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Pasword              string   `protobuf:"bytes,3,opt,name=pasword,proto3" json:"pasword,omitempty"`
	DisplayName          string   `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSignupRequest) Reset()         { *m = CreateSignupRequest{} }
func (m *CreateSignupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSignupRequest) ProtoMessage()    {}
func (*CreateSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{0}
}

func (m *CreateSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSignupRequest.Unmarshal(m, b)
}
func (m *CreateSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSignupRequest.Marshal(b, m, deterministic)
}
func (m *CreateSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSignupRequest.Merge(m, src)
}
func (m *CreateSignupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSignupRequest.Size(m)
}
func (m *CreateSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSignupRequest proto.InternalMessageInfo

func (m *CreateSignupRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateSignupRequest) GetPasword() string {
	if m != nil {
		return m.Pasword
	}
	return ""
}

func (m *CreateSignupRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type CreateSignupResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Uuid                 []byte   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSignupResponse) Reset()         { *m = CreateSignupResponse{} }
func (m *CreateSignupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSignupResponse) ProtoMessage()    {}
func (*CreateSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{1}
}

func (m *CreateSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSignupResponse.Unmarshal(m, b)
}
func (m *CreateSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSignupResponse.Marshal(b, m, deterministic)
}
func (m *CreateSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSignupResponse.Merge(m, src)
}
func (m *CreateSignupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSignupResponse.Size(m)
}
func (m *CreateSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSignupResponse proto.InternalMessageInfo

func (m *CreateSignupResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSignupResponse) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

type SignInRequest struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignInRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type Credentials struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{3}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{4}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateSignupRequest)(nil), "v1.CreateSignupRequest")
	proto.RegisterType((*CreateSignupResponse)(nil), "v1.CreateSignupResponse")
	proto.RegisterType((*SignInRequest)(nil), "v1.SignInRequest")
	proto.RegisterType((*Credentials)(nil), "v1.Credentials")
	proto.RegisterType((*SignInResponse)(nil), "v1.SignInResponse")
	proto.RegisterType((*User)(nil), "v1.User")
}

func init() { proto.RegisterFile("user-service.proto", fileDescriptor_2a3086c73a75cdba) }

var fileDescriptor_2a3086c73a75cdba = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0xda, 0xd2, 0x85, 0x69, 0x61, 0x8b, 0x59, 0x44, 0x14, 0x71, 0x08, 0x39, 0xa1, 0x42,
	0x93, 0x6d, 0xe9, 0xa9, 0x20, 0xf1, 0x53, 0x09, 0x89, 0x0b, 0x12, 0x29, 0x08, 0xc4, 0x05, 0x79,
	0x93, 0x51, 0x6a, 0x48, 0x6c, 0x63, 0x3b, 0x2d, 0xbb, 0x47, 0x1e, 0x01, 0x6e, 0x3c, 0x16, 0x48,
	0x3c, 0x01, 0x0f, 0x82, 0xe2, 0xb4, 0x6c, 0xbb, 0xa5, 0x97, 0xd6, 0xf3, 0xcd, 0x78, 0xbe, 0xf9,
	0x3e, 0x67, 0x80, 0x94, 0x1a, 0xd5, 0x40, 0xa3, 0x5a, 0xb0, 0x04, 0x43, 0xa9, 0x84, 0x11, 0xa4,
	0xb1, 0x18, 0x7a, 0xb7, 0x33, 0x21, 0xb2, 0x1c, 0x23, 0x2a, 0x59, 0x44, 0x39, 0x17, 0x86, 0x1a,
	0x26, 0xb8, 0xae, 0x2b, 0xbc, 0xfb, 0xf6, 0x2f, 0x19, 0x64, 0xc8, 0x07, 0x7a, 0x49, 0xb3, 0x0c,
	0x55, 0x24, 0xa4, 0xad, 0xd8, 0xad, 0x0e, 0xce, 0xe0, 0xc6, 0x54, 0x21, 0x35, 0x38, 0x63, 0x19,
	0x2f, 0x65, 0x8c, 0x9f, 0x4b, 0xd4, 0x86, 0xf4, 0xa0, 0x49, 0x25, 0x73, 0x1d, 0xdf, 0xb9, 0x7b,
	0x25, 0xae, 0x8e, 0xe4, 0x08, 0x2e, 0x61, 0x41, 0x59, 0xee, 0x36, 0x2c, 0x56, 0x07, 0xc4, 0x85,
	0x03, 0x49, 0xf5, 0x52, 0xa8, 0xd4, 0x6d, 0x5a, 0x7c, 0x1d, 0x92, 0x3b, 0xd0, 0x4d, 0x99, 0x96,
	0x39, 0x3d, 0xfd, 0xc0, 0x69, 0x81, 0x6e, 0xcb, 0xa6, 0x3b, 0x2b, 0xec, 0x25, 0x2d, 0x30, 0x78,
	0x04, 0x47, 0xdb, 0xdc, 0x5a, 0x0a, 0xae, 0xf1, 0x3f, 0xe4, 0x04, 0x5a, 0x65, 0xc9, 0x52, 0xcb,
	0xdd, 0x8d, 0xed, 0x39, 0x78, 0x0d, 0x57, 0xab, 0x7b, 0x2f, 0xf8, 0xfe, 0x99, 0x87, 0xd0, 0x49,
	0x14, 0xa6, 0xc8, 0x0d, 0xa3, 0xb9, 0xb6, 0xb7, 0x3b, 0xa3, 0xc3, 0x70, 0x31, 0x0c, 0xa7, 0xe7,
	0x70, 0xbc, 0x59, 0x13, 0x3c, 0x86, 0xce, 0x46, 0xee, 0x5c, 0xb5, 0xb3, 0xa9, 0xda, 0x83, 0xcb,
	0x92, 0xea, 0x5a, 0x76, 0x6d, 0xc7, 0xbf, 0x38, 0x08, 0xe0, 0xda, 0x7a, 0xac, 0x7d, 0x72, 0x82,
	0x19, 0xb4, 0xde, 0x68, 0x54, 0x7b, 0xba, 0x5f, 0x74, 0xae, 0xb1, 0xe3, 0x5c, 0xe5, 0x87, 0x12,
	0x39, 0xae, 0x3c, 0xb7, 0xe7, 0x11, 0x07, 0x52, 0x35, 0x9d, 0x8a, 0xa2, 0xa0, 0x3c, 0x9d, 0xd5,
	0x5f, 0x0d, 0x79, 0x07, 0xdd, 0x4d, 0x8f, 0xc9, 0xad, 0x95, 0xfa, 0x8b, 0x2f, 0xee, 0xb9, 0xbb,
	0x89, 0x7a, 0xfe, 0xe0, 0xe6, 0xd7, 0x5f, 0x7f, 0xbe, 0x37, 0x0e, 0x03, 0x88, 0x16, 0xc3, 0x48,
	0xdb, 0xdc, 0xc4, 0xe9, 0x8f, 0xde, 0x43, 0xaf, 0xe2, 0x7b, 0x55, 0xa2, 0x3a, 0x5d, 0xb3, 0x3d,
	0x87, 0x76, 0x2d, 0x9e, 0x5c, 0xaf, 0xda, 0x6d, 0xbd, 0x8f, 0x47, 0x36, 0xa1, 0x7d, 0xbd, 0x19,
	0x9f, 0x38, 0xfd, 0x67, 0xbf, 0x9d, 0x6f, 0x4f, 0x7f, 0x3a, 0x24, 0x87, 0x6e, 0x45, 0xe1, 0xaf,
	0x56, 0x20, 0x78, 0xbb, 0x1d, 0x93, 0x7b, 0x73, 0x63, 0xa4, 0x9e, 0x44, 0x51, 0xc6, 0xcc, 0xbc,
	0x3c, 0x09, 0x13, 0x51, 0x44, 0x42, 0x2f, 0x11, 0x57, 0xbf, 0xa9, 0x28, 0x28, 0xe3, 0x3a, 0xaa,
	0xf6, 0xc8, 0xf3, 0xd2, 0x33, 0xc6, 0x0d, 0x55, 0x3a, 0xfc, 0x94, 0xd3, 0x05, 0xe3, 0xfa, 0x49,
	0x56, 0xd9, 0x5d, 0x5d, 0x1a, 0x35, 0x87, 0xe1, 0x71, 0xdf, 0x71, 0x46, 0x3d, 0x2a, 0x65, 0xce,
	0x12, 0xbb, 0x21, 0xd1, 0x47, 0x2d, 0xf8, 0x64, 0x07, 0x89, 0x1f, 0x42, 0x73, 0x7c, 0x3c, 0x26,
	0x63, 0xe8, 0xc7, 0x68, 0x4a, 0xc5, 0x31, 0xf5, 0x97, 0x73, 0xe4, 0xbe, 0x99, 0xa3, 0xaf, 0x50,
	0x8b, 0x52, 0x25, 0xe8, 0xa7, 0x02, 0xb5, 0xcf, 0x85, 0xf1, 0xf1, 0x0b, 0xd3, 0x26, 0x24, 0x6d,
	0x68, 0xfd, 0x68, 0x38, 0x07, 0x27, 0x6d, 0xbb, 0x75, 0x0f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x8d, 0xe2, 0xb0, 0xdf, 0xdb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserCommandServiceClient is the client API for UserCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCommandServiceClient interface {
	// Create new signup request
	CreateSignup(ctx context.Context, in *CreateSignupRequest, opts ...grpc.CallOption) (*CreateSignupResponse, error)
}

type userCommandServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserCommandServiceClient(cc *grpc.ClientConn) UserCommandServiceClient {
	return &userCommandServiceClient{cc}
}

func (c *userCommandServiceClient) CreateSignup(ctx context.Context, in *CreateSignupRequest, opts ...grpc.CallOption) (*CreateSignupResponse, error) {
	out := new(CreateSignupResponse)
	err := c.cc.Invoke(ctx, "/v1.UserCommandService/CreateSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCommandServiceServer is the server API for UserCommandService service.
type UserCommandServiceServer interface {
	// Create new signup request
	CreateSignup(context.Context, *CreateSignupRequest) (*CreateSignupResponse, error)
}

// UnimplementedUserCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserCommandServiceServer struct {
}

func (*UnimplementedUserCommandServiceServer) CreateSignup(ctx context.Context, req *CreateSignupRequest) (*CreateSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSignup not implemented")
}

func RegisterUserCommandServiceServer(s *grpc.Server, srv UserCommandServiceServer) {
	s.RegisterService(&_UserCommandService_serviceDesc, srv)
}

func _UserCommandService_CreateSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCommandServiceServer).CreateSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserCommandService/CreateSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCommandServiceServer).CreateSignup(ctx, req.(*CreateSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserCommandService",
	HandlerType: (*UserCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSignup",
			Handler:    _UserCommandService_CreateSignup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service.proto",
}

// UserQueryServiceClient is the client API for UserQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserQueryServiceClient interface {
	// SignIn ...
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type userQueryServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserQueryServiceClient(cc *grpc.ClientConn) UserQueryServiceClient {
	return &userQueryServiceClient{cc}
}

func (c *userQueryServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/v1.UserQueryService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServiceServer is the server API for UserQueryService service.
type UserQueryServiceServer interface {
	// SignIn ...
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
}

// UnimplementedUserQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserQueryServiceServer struct {
}

func (*UnimplementedUserQueryServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}

func RegisterUserQueryServiceServer(s *grpc.Server, srv UserQueryServiceServer) {
	s.RegisterService(&_UserQueryService_serviceDesc, srv)
}

func _UserQueryService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserQueryService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserQueryService",
	HandlerType: (*UserQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _UserQueryService_SignIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service.proto",
}
